In [6]:
import numpy as np

In [9]:
# Runs Scored by player in 4 matches
Virat_runs = np.array([72,45,88,101])
print(Virat_runs)

[ 72  45  88 101]


In [10]:
team_runs = np.array([
[72,45,88],
[55,60,47],
[30,56,75]
])

In [11]:
print(team_runs)

[[72 45 88]
 [55 60 47]
 [30 56 75]]


In [12]:
player_ages = np.array((35,37,31))
print(player_ages)

[35 37 31]


In [20]:
#Special Arrays
zeros = np.zeros((2,3))
ones = np.ones((3,2))
identity = np.eye(3)
print(zeros)
print(ones)
print(identity)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
empty = np.empty((2,2)) # uninitialized garbage float array
full = np.full((2,2),7)
print(empty)
print(full)

[[3.56e-322 2.22e-322]
 [4.35e-322 4.99e-322]]
[[7 7]
 [7 7]]


In [30]:
# Creating arrays with range
arr = np.arange(55,65) # start: 55, end:64
print(arr, arr[0] , arr[5], arr[9])
arr[4] = 99
print(arr[4])

[55 56 57 58 59 60 61 62 63 64] 55 60 64
99


In [31]:
run_rates = np.arange(4,11,1)
print(run_rates)

[ 4  5  6  7  8  9 10]


In [32]:
#linspace
batting_avg = np.linspace(30,50,5) # here 5 is not a step it is the 5 evenly spread number (total 5)
print(batting_avg)

[30. 35. 40. 45. 50.]


In [33]:
strike_rates = np.random.uniform(100,200,10)
print(strike_rates)

[175.01673759 152.50919743 151.18453306 160.03931109 142.60947575
 144.23912126 196.76653648 174.38552381 129.37789203 148.98485384]


In [34]:
runs = np.random.randint(1,151,(2,3))
print(runs)

[[36 83  4]
 [50 25 77]]


In [35]:
batting_avg = np.random.normal(40,5,(2,3))
print(batting_avg)

[[43.40014691 40.34559548 51.58764381]
 [46.97029476 37.88384418 29.78808277]]


In [38]:
# Adding new values to an existing array 
arr = np.arange(0,10)
new_arr_single = np.append(arr,10)
new_arr_multiple = np.append(arr, [10,11,12])
print(arr)
print(new_arr_single)
print(new_arr_multiple)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [39]:
#Reshaping
marks = np.arange(50, 62)
print(marks)
reshaped = marks.reshape(3,4)
print(reshaped)

[50 51 52 53 54 55 56 57 58 59 60 61]
[[50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]]
