In [1]:
import numpy as np

In [3]:
arr  = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
# Basic Arithematic
print(arr + arr)
print(arr * arr)
print(arr - arr)
print(arr / arr)
print(arr ** 3)
print(np.sqrt(arr))


[ 2  4  6  8 10 12 14 16 18]
[ 1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  1   8  27  64 125 216 343 512 729]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [7]:
# Summary statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var()) # Variance
print(arr.std()) # standard deviation

45
5.0
9
1
6.666666666666667
2.581988897471611


In [9]:
# Reversing an array
arr = np.array([1,2,3,4,5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 3 2 1]


In [10]:
# Sorting an array
arr = np.array([5,2,8,1,3])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 5 8]


In [12]:
# For descending
sorted_arr = np.sort(arr)[::-1] # Reverse the array
print(sorted_arr)

[8 5 3 2 1]
