In [1]:
#Indexing, Slicing, Filtering numpy arrays
import numpy as np

In [2]:
marks = np.array([55,68,72,49,83,91,37,65,78,59,88])
print(marks)

[55 68 72 49 83 91 37 65 78 59 88]


In [4]:
# indexing and slicing
print(marks[8]) # 9th student
print(marks[1:5])
print(marks[0:5])

78
[68 72 49 83]
[55 68 72 49 83]


In [5]:
# Broadcasting (Update multiple values)
marks[0:3] = 75
print(marks)

[75 75 75 49 83 91 37 65 78 59 88]


In [6]:
#Vectorization
result = marks + 5
print(result)

[80 80 80 54 88 96 42 70 83 64 93]


In [7]:
# Reset Array
marks = np.array([55,68,72,49,83,91,37,65,78,59,88])

In [8]:
# Slices and Copy
top_batch = marks[0:5] # "View" or "Shallow copy"
print(top_batch)

[55 68 72 49 83]


In [10]:
# Modify slice (affects original)
top_batch[:] = 99
print(top_batch)
print(marks)

[99 99 99 99 99]
[99 99 99 99 99 91 37 65 78 59 88]


In [11]:
# To avoid this,use copy()
marks = np.array([55,68,72,49,83,91,37,65,78,59,88])
marks_copy = marks.copy() # deep copy
marks_copy[3] = 99
print(marks_copy)
print(marks)

[55 68 72 99 83 91 37 65 78 59 88]
[55 68 72 49 83 91 37 65 78 59 88]


In [12]:
# Conditional Selection
marks = np.array([69,26,78,91,54,34])
print(marks)

[69 26 78 91 54 34]


In [15]:
passed = marks >= 35 # boolean array
print(passed)
print(marks[passed]) #actual value

[ True False  True  True  True False]
[69 78 91 54]
